version: '3'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./app:/app
      - ./conf.d:/etc/nginx/conf.d
    ports:
      - 3300:80

  php:
    image: php:7.4.10-fpm-alpine
    volumes:
      - ./app:/app
